sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: SmDPgPL4TyYCqXFyQJlX98/fXevqXWlEPYes7fRUi/LfNwyFpWpd0de9Ke4T0PKBLlzTOHVkB2l2cQsA6ARKQ+TuIzp9LGXYjRaXcL9+HbL9W+sGyS3u5hyBJ2EdPXGQdyArW90RHxI0rFZGB6g8XzUVX+GRG7m/vWOLTNDUynf6dmdU6WQ1+LHU4rghJPSCq0lVFHV1vqiC6vxwhc9ryIU1Qs3bwl0/y80JYmskSnHcAnX6GiS2VKmAIs72ccXSL30HZzH2aDVru9FTm/sZcTZf4N2I6zOefukhsEUHaqWy4/fJ7kNWQGIXiKnO86tsUa2JvzrqWNdxi6LbQPD54Bw1t9cf99HjSsz9v3lpigzvWaYwRcldvFQotWsrvpWna8K4VnOwD+/rMCtpu0zOliJdWRps3NJnAp1kz4ihGKqhTyUTDVBK4zbQhuaK1gN4gCcML4WcUpT/a8bPQydp8anw+a/9czh8D7c7qf/kUfx9nCbn22m3nXKJDAldL32z881B7WU4EgRTDW/ojyLUPyVuRIq6zRtufZYUg9FWzd05+U8jb/wgrkyf8q24Y/q87+1DqS2xDZkGubdogupPfe2P92EQIGtsEEAPfFD2uqGHeACGcmxs+cKv8sFTfzj2wX+nV7Ba0m63sTg1pC5mbCNctjzfWoRkOm/sGL20YxU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Paste-Jewels_4930
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy